#define NUM_CONSTRUCT_VERBS 101
#define NUM_DESTRUCT_VERBS 100
#define MAX_VERB_LENGTH 15

#define NUM_NOUNS 100
#define MAX_NOUN_LENGTH 15

#define TECHNOLENGTH MAX_NOUN_LENGTH + MAX_VERB_LENGTH

#include <time.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>

const char constructiveVerbs[NUM_CONSTRUCT_VERBS][MAX_VERB_LENGTH] = {
  "Aligning ",
  "Building ",
  "Calibrating ",
  "Instancing ",
  "Configuring ",
  "Snorting ",
  "Microwaving ",
  "Tweaking ",
  "Wrangling ",
  "Hacking ",
  "Pwning ",
  "Booting ",
  "Allocating ",
  "Binding ",
  "Revving ",
  "Polishing ",
  "Fabricating ",
  "Pinging ",
  "Refactoring ",
  "Loading ",
  "Quantifying ",
  "Assembling ",
  "Distilling ",
  "Baking ",
  "Receiving ",
  "Unlocking ",
  "Compiling ",
  "Pressurizing ",
  "Chooching ",
  "Making ",
  "Engaging ",
  "Decrypting ",
  "Synthesizing ",
  "Predicting ",
  "Analyzing ",
  "Dispensing ",
  "Firing ",
  "Inserting ",
  "Aligning ",
  "Encouraging ",
  "Extruding ",
  "Accessing ",
  "Sharpening ",
  "Enhancing ",
  "Cranking ",
  "Stacking ",
  "Crafting ",
  "Rendering ",
  "Mounting ",
  "Generating ",
  "Implementing ",
  "Downloading ",
  "Constructing ",
  "Wow! Amazing ",
  "Moistening ",
  "Customizing ",
  "Compensating ",
  "Buffering ",
  "Transferring ",
  "Inducting ",
  "Emitting ",
  "Unzipping ",
  "Squirting ",
  "Feeding ",
  "Buying ",
  "Sparking ",
  "Implanting ",
  "Triangulating ",
  "Injecting ",
  "Linking ",
  "Brewing ",
  "Processing ",
  "Deploying ",
  "Tuning ",
  "Attaching ",
  "Training ",
  "Ignoring ",
  "Tapping ",
  "Reloading ",
  "Simulating ",
  "Fluffing ",
  "Filling ",
  "Sorting ",
  "Updating ",
  "Upgrading ",
  "Priming ",
  "Tracing ",
  "Inflating ",
  "Wangjangling ",
  "Charging ",
  "Cracking ",
  "Ignoring ",
  "Activating ",
  "Dialing ",
  "Pimping ",
  "Collecting ",
  "Approaching ",
  "Approving ",
  "Sampling ",
  "Energizing ",
  "Stuffing "
};

const char destructiveVerbs[NUM_DESTRUCT_VERBS][MAX_VERB_LENGTH] = {
  "Deallocating ",
  "Trashing ",
  "Unplugging ",
  "Revoking ",
  "Forgetting ",
  "Discarding ",
  "Dropping ",
  "Holstering ",
  "Shredding ",
  "Jettisoning ",
  "Dissolving ",
  "Liquidating ",
  "Releasing ",
  "Collimating ",
  "Ejecting ",
  "Ditching ",
  "Leaking ",
  "Selling ",
  "Banishing ",
  "Dereferencing ",
  "Sacrificing ",
  "Desoldering ",
  "Destructing ",
  "Decompiling ",
  "Blowing ",
  "Disengaging ",
  "Digesting ",
  "Smashing ",
  "Encrypting ",
  "Crashing ",
  "Locking ",
  "Purging ",
  "Regretting ",
  "Rewinding ",
  "Freeing ",
  "Deleting ",
  "Closing ",
  "Retracting ",
  "Collapsing ",
  "Liquefying ",
  "Derezzing ",
  "Stowing ",
  "Archiving ",
  "Suspending ",
  "Suppressing ",
  "Cleaning ",
  "Squashing ",
  "Securing ",
  "Withdrawing ",
  "Dumping ",
  "Obfuscating ",
  "Breaking ",
  "Scrubbing ",
  "Abandoning ",
  "Flattening ",
  "Stashing ",
  "Finishing ",
  "Evacuating ",
  "Scrambling ",
  "Recycling ",
  "Crushing ",
  "Zipping ",
  "Unloading ",
  "Disconnecting ",
  "Loosening ",
  "Containing ",
  "Debating ",
  "Detaching ",
  "Neutralizing ",
  "Salvaging ",
  "Emptying ",
  "Hiding ",
  "Disarming ",
  "Pickling ",
  "Disregarding ",
  "Yeeting ",
  "Scrapping ",
  "Deflating ",
  "Discharging ",
  "Deactivating ",
  "Sterilizing ",
  "Relieving ",
  "Nuking ",
  "Degaussing ",
  "Dismissing ",
  "Draining ",
  "Rejecting ",
  "Nerfing ",
  "Paying ",
  "Returning ",
  "Unsticking ",
  "Splitting ",
  "Cancelling ",
  "Shaming ",
  "Embezzling ",
  "Flinging ",
  "Regretting ",
  "Halting ",
  "Arresting ",
  "Burying "
};

const char nouns[NUM_NOUNS][MAX_NOUN_LENGTH] = {
  "content...",
  "your mom...",
  "the shmoo...",
  "API...",
  "the BJT man...",
  "aesthetics...",
  "backstory...",
  "tactics...",
  "bugs...",
  "sauce...",
  "warp drive...",
  "data...",
  "the funk...",
  "AI...",
  "crystals...",
  "spaghetti...",
  "fluxgate...",
  "electrons...",
  "loud noises...",
  "wires...",
  "bytecode...",
  "the truth...",
  "magic...",
  "hot lava...",
  "bits...",
  "Brad...",
  "Teensy...",
  "sensors...",
  "photons...",
  "signal...",
  "the planet...",
  "password...",
  "chips...",
  "circuits...",
  "privacy...",
  "synergy...",
  "widgets...",
  "love...",
  "packets...",
  "reality...",
  "lasers...",
  "protocols...",
  "voltage...",
  "registers...",
  "puns...",
  "dogecoins...",
  "kittens...",
  "magic smoke...",
  "plot device...",
  "the core...",
  "dank memes...",
  "subroutines...",
  "radiation...",
  "steam...",
  "trousers...",
  "beer...",
  "protocol...",
  "one-liners...",
  "the Gibson...",
  "software...",
  "a fat one...",
  "holograms...",
  "magnets...",
  "inductors...",
  "resistors...",
  "capacitors...",
  "viewers...",
  "subscribers...",
  "sausage...",
  "my wife...",
  "drama...",
  "the future...",
  "vectors...",
  "the clowns...",
  "a Palm Pilot...",
  "5G implant...",
  "monkeys...",
  "breadboard...",
  "Patreon...",
  "money...",
  "the Internet...",
  "fluids...",
  "the impostor...",
  "beats...",
  "dopamine...",
  "fedora...",
  "neural net...",
  "comments...",
  "ports...",
  "you. Yes you...",
  "mixtape...",
  "[REDACTED]...",
  "hot tub...",
  "paperwork...",
  "Nerf...",
  "cyber-doobie...",
  "the 1%...",
  "the Matrix...",
  "variables...",
  "IP address..."
};

char* genTechnobabble(char* technobabble, uint8_t constructive) {

	/// Randomly selects a verb and gets its length
	int verbNumber = rand() % ((constructive ? NUM_CONSTRUCT_VERBS : NUM_DESTRUCT_VERBS));

	/// Randomly selects a noun and gets its length
	int nounNumber = rand() % (NUM_NOUNS);

	strncpy(technobabble, (constructive ? constructiveVerbs[verbNumber] : destructiveVerbs[verbNumber]), MAX_VERB_LENGTH);
	strncat(technobabble, nouns[nounNumber], MAX_NOUN_LENGTH);

	return technobabble;

}
